### PR TITLE
Use BTreeMap for dependencies for stable results

### PR DESCRIPTION
**Pull request by indutny**
I figured it out! HashMaps are unsorted and the issue with the instability of the test had more todo with that than parallelism.

### CODE REVIEW

**Comment by indutny** [comment]
@zkat how would you feel about reviewing/merging this? Asking since I decide whether to base my work on main or on this branch.

**Comment by zkat** [comment]
oh geez, I didn't see the notification about this! Absolutely yes! Awesome!

**Comment by indutny** [comment]
No worries. Thank you for merging it!

**Comment by zkat** [comment]
Honestly I should've known better. I had totally run into issues with JavaScript ones being offered before lol

**Pull request merged**
