### PR TITLE
Setup oro-pack crate and define a struct

### PR DESCRIPTION
**Pull request by jlkiri**
This PR creates a new `oro-pack` crate and defines an `OroPack` struct with some basic methods and tests.
I will add methods one by one in following PRs.

### CODE REVIEW

**Comment by zkat** [comment]
Can we have this be a feature branch while you work on it? I'd like a bit more functionality in this crate before merging it to main.

**Comment by jlkiri** [comment]
Sure, is there some kind of develop branch? Or I can create a feature branch directly in this repository? I just want to avoid huge PRs

**Comment by jlkiri** [comment]
Ah, I realized that I can just keep pushing here after merging smaller branches into this one

**Comment by zkat** [comment]
Yep! I'm gonna convert this to a draft PR in the meantime :)

**Comment by zkat** [comment]
@jlkiri I forgot to mention this in the issue, but this might be of help... these are the tests I wrote for the NPM cli itself that check most of the scenarios (others are tested by npm-packlist itself): https://github.com/npm/cli/blob/latest/test/tap/pack-files-and-ignores.js

**Comment by jlkiri** [comment]
@zkat I've added quite a bit of functionality and it seems to be working. Here's what it does and what it does not do:

## Does

* Walk the project directory recursively
* Read `package.json` and respect `files` field when present
* Read `.gitignore` and apply it
* Ignore all kinds of system files like `DS_Store` but  can include them if in `files`
* Ignore top-level `node_modules`
* Always include files like `README` or `LICENSE`

## Does not

* Follow symlinks (or rather I haven't thought about it yet)
* Respect `bundleDependencies`

**Comment by zkat** [comment]
Wow, this is amazing! Thanks so much. Would you like to submit this contribution for membership in the xlcollab, btw? (so you would license it under Parity and get voting rights on licensing issues). You'd be most welcome, I think! :)

**Comment by jlkiri** [comment]
@zkat Yes, why not :)

**Comment by zkat** [comment]
@chrisdickinson @felipesere vote time :)

**Comment by zkat** [comment]
I'm 👍 btw

**Comment by felipesere** [comment]
I vote *yes*. 👍

**Comment by zkat** [comment]
(that's a majority, so welcome!)

**Comment by zkat** [comment]
@all-contributors please add @jlkiri for code

**Pull request merged**
