### PR TITLE
get CI to be green again

### PR DESCRIPTION
**Pull request by zkat**

### CODE REVIEW

**Comment by zkat** [comment]
@indutny heads up that I disabled the resolver tests in this PR. The new resolver algorithm turned out to be fairly unstable in its results (no surprise), but I wonder if your tree optimizer will end up making it predictable again, in which case we can bring these tests back. I'm at a loss on how to test the resolver otherwise.

**Comment by indutny** [comment]
Makes sense. I wonder if we could mock nassun somehow (maybe make it a trait and pass a different thing) so that it would be predictable and won't require network connection?

**Comment by zkat** [comment]
the tests already mock a local web server. This is more the resolver algorithm itself being unpredictable when there's dependency conflicts, about who gets nested.

**Comment by indutny** [comment]
Got it. I was thinking about eliminating networking and thus unpredictability altogether. Although, I agree that it makes sense to test it with a mock server as well, but if we'd have former - we could check the results against a snapshot of lock file since it'll be stable.

**Pull request merged**
